### ISSUE TITLE
Estimated Date is all over the Place

### ISSUE THREAD

**Issue by InvisibleSymbol** [mohamedmansour/ethereum-burn-stats#28]
I think you are only using the current block time to calculate the estimate, which doesn't work due to the random nature of mining.

Since you already store blocks in-browser for the chart and list, I would suggest to average their Block time for a more stable estimate.

**Comment by InvisibleSymbol** [comment]
Looking at the code, it seems you are actually using 5 block for an average, I guess that's just not enough to make a nice estimate. 
![](https://url.invis.cloud/yVpQbK)
May I suggest to use the etherscan api for a better estimate? https://api.etherscan.io/api?module=block&action=getblockcountdown&blockno=12965000

**Comment by mohamedmansour** [comment]
@InvisibleSymbol it is because it is impossible to know how fast each block is. It will still be the same if we use etherscan API, what they do differently  is that they don't update the webpage if you did it request it once so its not real-time. But if you refresh etherscanAPI, they will have the same jump.

What I should do is increase that estimate the number of blocks you have already seen most likely to increase precision and make it less bumpy.

**Comment by mohamedmansour** [comment]
I deployed the one without any block count limitation, it is a bit more stable, but when the bursts happen it might scale back more

**Comment by InvisibleSymbol** [comment]
> But if you refresh etherscanAPI, they will have the same jump.

But it doesn't, because they use a very large time frame for their average Block time, somewhere in the thousands of Blocks I assume.

I wrote a simple Script that calculates the Block Time they use based on the estimate they return, and it's pretty stable while still not being a naive 13sec. 

`seconds_per_blocks = response["EstimateTimeInSec"] / response["RemainingBlock"]`
```
Block 12897169: Api used an average of 13.4002211378s/Block
MH
Block 12897171: Api used an average of 13.4002211443s/Block
MMMMMMMH
Block 12897172: Api used an average of 13.4002211476s/Block
H
Block 12897174: Api used an average of 13.4002211541s/Block
MMMMH
Block 12897175: Api used an average of 13.4002211574s/Block
MH
Block 12897176: Api used an average of 13.4002211607s/Block
H
Block 12897177: Api used an average of 13.4002211639s/Block
H
Block 12897179: Api used an average of 13.4002211704s/Block
H
Block 12897180: Api used an average of 13.4002211737s/Block
MH
Block 12897181: Api used an average of 13.4002211770s/Block
MH
Block 12897182: Api used an average of 13.4002211802s/Block
MMMMMMMH
Block 12897183: Api used an average of 13.4002211835s/Block
H
Block 12897184: Api used an average of 13.4002211867s/Block
H
Block 12897185: Api used an average of 13.4002211900s/Block
MH
Block 12897186: Api used an average of 13.4002211933s/Block
H
Block 12897187: Api used an average of 13.4002211965s/Block
H
Block 12897188: Api used an average of 13.4002211998s/Block
H
Block 12897190: Api used an average of 13.4002212063s/Block
MH
Block 12897191: Api used an average of 13.4002212096s/Block
...
```

**Comment by mohamedmansour** [comment]
From Nick on Twitter:

> An easy option that works better is with n blocks to go, fetch the timestamp of the block n blocks ago and add that to the current time.

https://twitter.com/nicksdjohnson/status/1419498696085889024
